package by.homework.lessons.Task20;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;
import java.util.concurrent.*;

public class FileGenerator implements Callable<List<String>> {

    // Путь к папке для файлов (относительно корня проекта)
    private static final String TARGET_DIR_PATH = "src/by/homeworks/lessons/Task20/files";

    private final String taskId;
    private final Path targetDirectory;

    public FileGenerator(int id) {
        this.taskId = "Task-" + id;
        this.вirectory = Paths.get(TARGET_DIR_PATH);

    }

    @Override
    public List<String> call() throws Exception {
        String threadName = Thread.currentThread().getName();

        // Формируем полный путь к файлу
        String fileName = taskId + "_" + UUID.randomUUID().toString().substring(0, 8) + ".txt";
        Path filePath = targetDirectory.resolve(fileName);

        System.out.println("[" + threadName + "] -> " + taskId + ": Начинаю создание файла: " + filePath.toAbsolutePath());

        List<String> contentLines = new ArrayList<>();
        // Используем ThreadLocalRandom для потокобезопасности и скорости
        long sleepTimeMs = 1000 + ThreadLocalRandom.current().nextInt(2001);

        // Генерация 10 произвольных строк
        for (int i = 0; i < 10; i++) {
            contentLines.add("Line " + (i + 1) + " generated by " + threadName);
        }

        // Запись в файл
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(filePath.toFile()))) {
            for (String line : contentLines) {
                writer.write(line);
                writer.newLine();
            }
        } catch (IOException e) {
            System.err.println("[" + threadName + "] -> Ошибка записи файла: " + e.getMessage());
            throw e;
        }

        System.out.println("[" + threadName + "] -> " + taskId + ": Файл создан. Засыпаю на " + sleepTimeMs + " мс...");

        Thread.sleep(sleepTimeMs);

        System.out.println("[" + threadName + "] -> " + taskId + ": Проснулся. Задача завершена.");

        return Collections.singletonList(filePath.toString());
    }

    public static void main(String[] args) {
        int totalTasks = 10;
        int poolSize = 3;

        ExecutorService executor = Executors.newFixedThreadPool(poolSize);
        List<Future<List<String>>> futures = new ArrayList<>();

        System.out.println("=== СТАРТ ПРОГРАММЫ (FileGenerator) ===");
        System.out.println("Целевая папка: " + Paths.get(TARGET_DIR_PATH).toAbsolutePath().toString());
        System.out.println("Запущено задач: " + totalTasks);
        System.out.println("Размер пула потоков: " + poolSize);
        System.out.println("-----------------------------------");

        for (int i = 0; i < totalTasks; i++) {
            Callable<List<String>> task = new FileGenerator(i);
            Future<List<String>> future = executor.submit(task);
            futures.add(future);
        }

        List<String> allCreatedFiles = new ArrayList<>();

        for (Future<List<String>> future : futures) {
            try {
                List<String> result = future.get();
                allCreatedFiles.addAll(result);
            } catch (InterruptedException | ExecutionException e) {
                System.err.println("Ошибка при получении результата задачи: " + e.getMessage());
                Thread.currentThread().interrupt();
            }
        }

        executor.shutdown();

        System.out.println("===================================");
        System.out.println("ВСЕ ЗАДАЧИ ВЫПОЛНЕНЫ");
        System.out.println("Всего создано файлов: " + allCreatedFiles.size());
        System.out.println("Файлы сохранены в: " + Paths.get(TARGET_DIR_PATH).toAbsolutePath());

        // Вывод списка файлов
        allCreatedFiles.forEach(System.out::println);
    }
}