package by.homework.lessons.Task20;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

public class Main2 implements Callable<List<String>> {

    private String taskId;

    public Main2(int id) {
        this.taskId = "Task: " + id;
    }

    @Override
    public List<String> call() throws Exception {
        String threadName = Thread.currentThread().getName();
        // Генерируем уникальное имя файла
        String fileName = taskId + "_" + UUID.randomUUID().toString().substring(0, 3) + ".txt";

        // ЛОГ: Начало работы потока
        System.out.println("[" + threadName + "] -> " + taskId + ": Начинаю создание файла: " + fileName);

        List<String> contentLines = new ArrayList<>();
        Random random = new Random();

        // Генерация 10 произвольных строк
        for (int i = 0; i < 10; i++) {
            contentLines.add("Line " + (i + 1) + " generated by " + threadName);
        }

        // Запись в файл
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(fileName))) {
            for (String line : contentLines) {
                writer.write(line);
                writer.newLine();
            }
        } catch (IOException e) {
            System.err.println("[" + threadName + "] -> Ошибка записи файла: " + e.getMessage());
            throw e;
        }

        // Случайная задержка от 1 до 3 секунд (1000 + 0..2000)
        int sleepMillis = 1000 + random.nextInt(2001);
        System.out.println("[" + threadName + "] -> " + taskId + ": Файл создан. Засыпаю на " + sleepMillis + " мс...");

        Thread.sleep(sleepMillis);

        System.out.println("[" + threadName + "] -> " + taskId + ": Проснулся. Задача завершена.");

        // Возвращаем коллекцию имен файлов (в данном случае список из одного элемента)
        return Collections.singletonList(fileName);
    }

    public static void main(String[] args) {
        int totalTasks = 10;
        int poolSize = 3;

        // Создаем пул из 3 потоков
        ExecutorService executor = Executors.newFixedThreadPool(poolSize);
        List<Future<List<String>>> futures = new ArrayList<>();

        System.out.println("=== СТАРТ ПРОГРАММЫ ===");
        System.out.println("Запущено задач: " + totalTasks);
        System.out.println("Размер пула потоков: " + poolSize);
        System.out.println("-----------------------------------");

        // Отправка 10 задач в пул
        for (int i = 0; i < totalTasks; i++) {
            Callable<List<String>> task = new Main2(i);
            Future<List<String>> future = executor.submit(task);
            futures.add(future);
        }

        List<String> allCreatedFiles = new ArrayList<>();

        // Сбор результатов
        for (Future<List<String>> future : futures) {
            try {
                // get() блокирует выполнение, пока задача не будет готова
                List<String> result = future.get();
                allCreatedFiles.addAll(result);
            } catch (InterruptedException | ExecutionException e) {
                System.err.println("Ошибка при получении результата задачи: " + e.getMessage());
                Thread.currentThread().interrupt(); // Восстанавливаем статус прерывания
            }
        }

        executor.shutdown();

        System.out.println("===================================");
        System.out.println("ВСЕ ЗАДАЧИ ВЫПОЛНЕНЫ");
        System.out.println("Всего создано файлов: " + allCreatedFiles.size());
        System.out.println("Список файлов: " + allCreatedFiles);
    }
}